### ISSUE TITLE
 /root/config.sh in mysql Dockerfile

### ISSUE THREAD

**Issue by Ali-Rizwan-Ashraf** [instana/robot-shop#22]
The permission to file config.sh aren't given in docker file 
building the container gives error code 126

COPY config.sh /root/
RUN /root/config.sh

**Comment by Ali-Rizwan-Ashraf** [comment]
Giving permission by using this line
RUN chmod +x /root/config.sh
works.

Dockerfile 
COPY config.sh /root/
RUN chmod +x /root/config.sh
RUN /root/config.sh

**Comment by steveww** [comment]
The file has 755 permissions so it copy in to the container with matching permissions. Are you running on a Windows machine?

**Comment by Ali-Rizwan-Ashraf** [comment]
nope i used it in ubuntu 18, but via azure release pipeline

**Comment by steveww** [comment]
I see. Looks like the pipeline messes with the file permissions. Interesting that it only did it for the mysql image and not the others, there are scripts copied in for the other images too. Please have a dig and see if you can figure out what the pipeline is doing.

**Comment by Ali-Rizwan-Ashraf** [comment]
Sure, i'll try to figure out
