### ISSUE TITLE
Getting connection error when calling to payment api in Openshft

### ISSUE THREAD

**Issue by isushilksharma** [instana/robot-shop#27]
I've simply put all the services in openshift (with deploy.sh in Openshift dir), but when I click on pay now, it throws connection error - 

**Please investigate it as it is coming always, in any openshift version.**

Log
--------------------------------
`[2020-01-27 11:25:48,138] ERROR in payment: HTTPSConnectionPool(host='paypal.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff9e85cc0b8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))`

**Comment by steveww** [comment]
Looks like a DNS issue. Double check that DNS is working for external names in your cluster.

**Comment by isushilksharma** [comment]
Do I have to change something in container or **/etc/hosts** of host machine? Because, the same images are running fine with docker only.

**Comment by steveww** [comment]
The payment service just makes a HTTP GET call to paypal.com, you can see this in the message. For some reason it can not resolve the address, looks like a DNS issue to me. Run a shell in the payment container and check the DNS functionality.

**Comment by isushilksharma** [comment]
It didn't worked at all .. not able to figure it out what's happening..

**Comment by steveww** [comment]
This is a problem with your environment and name resolution. Closing this issue.
