### ISSUE TITLE
helm deployment redis stays pending

### ISSUE THREAD

**Issue by hamzahda** [instana/robot-shop#53]
I'm trying to deploy the app on a kubernetes cluster built using kubeadm and when helm install redis stays in a pending status

**Comment by rohanarora** [comment]
Have you attempted doing a:
```
kubectl describe pod pod_name
```
The pending status might very well be due to insufficient resources e.g CPU or memory.

**Comment by steveww** [comment]
What flavour of K8s?
Redis is a stateful set and uses persistent volume claims. These are handled differently by different K8s flavours. The helm chart has settings for vanilla and Openshift.

To see what's happening in your K8s cluster, I highly recommend https://github.com/lensapp/lens I use it all the time.

**Comment by Angi2412** [comment]
I had the same problem. I could solve it by adding a persistent volume into the Redis YAML file.
See her https://github.com/instana/robot-shop/issues/54#issuecomment-780045228

**Comment by steveww** [comment]
As already mentioned this is a storage class configuration issue. I've not tested with Docker desktop implementation of K8s.

Take a look in values.yaml and the template for the Redis statefulset, the storage class can be tweaked.
