### ISSUE TITLE
root/config.sh: not found

### ISSUE THREAD

**Issue by QAInsights** [instana/robot-shop#68]
I am trying to docker build in Windows. I am getting below error. I tried chmod to the sh file, still the issue persists.

```
root/config.sh: not found
```

**Comment by steveww** [comment]
Sorry windows is not supported. You don’t need to build your own images, there are published to Docker Hub. If you must build your own, just a VM on a cloud provider of your choice.  

Sent from my iPhone

On 12 Jul 2021, at 20:35, NaveenKumar Namachivayam ⚡ ***@***.***> wrote:

﻿


I am trying to docker build in Windows. I am getting below error. I tried chmod to the sh file, still the issue persists.


root/config.sh: not found

**Comment by QAInsights** [comment]
Thanks @steveww does it support WSL? Please clarify.

**Comment by steveww** [comment]
Vanilla Linux only. 

Sent from my iPhone

On 13 Jul 2021, at 16:08, NaveenKumar Namachivayam ⚡ ***@***.***> wrote:

﻿


Thanks @steveww does it support WSL? Please clarify.

**Comment by QAInsights** [comment]
Thanks. I am closing this issue.
