### ISSUE TITLE
DC/OS deployment files for new PHP service

### ISSUE THREAD

**Issue by steveww** [instana/robot-shop#9]
New PHP ratings service needs matching DC/OS deployment files.

**Comment by kcrawley** [comment]
@steveww please grant me write access to the repo so I don't have to mess with forks to submit a PR/merge.

**Comment by steveww** [comment]
Just do a PR until I figure out access rules.

**Comment by kcrawley** [comment]
Steve, I’ll be back from vacation next week so it can wait. Please let me know when it’s sorted out.

Cheers

**Comment by steveww** [comment]
Not much interest in DC/OS, K8s won the battle.
